# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_electron_on_windows:
    runs-on: windows-latest
    steps:

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14
      
      - name: install dependencies
        run: npm install

      - name: build electron
        run: npm run build-electron:win

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dicom-viewer-app
          path: dist

      - name: upload artifacts
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: dist
          destination: dicom-viewer-dac76.appspot.com/${{github.event.inputs.version}}
