# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_electron_on_windows:
    runs-on: windows-latest
    steps:

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14
      
      - name: install dependencies
        run: npm install

      - name: build electron
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: build-electron:win
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

      - name: upload artifacts
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: dist
          destination: dicom-viewer-dac76.appspot.com/artifacts
